name: file_manager_ripgrep_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  injectable: ^3.0.0
  get_it: ^9.2.1

dev_dependencies:
  injectable_generator: ^3.1.0
  build_runner: ^2.15.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
